[hosts]
human_genome: /home/billy/raid_mount/billy/human_host/human

[settings]
bypass_log_name: bypass_log.txt

[scripts]
#sam_sift: /quackers_pipe/scripts/sam_sift.py
#clean_reads_reconcile: /home/billy/raid_mount/billy/test_alz/scripts/clean_reads_reconcile.py
#AR_reconcile: /quackers_pipe/scripts/AR_reconcile.py
#contig_reconcile: /home/billy/raid_mount/billy/test_alz/scripts/contig_reconcile.py
#orphanizer: /home/billy/raid_mount/billy/test_alz/scripts/read_orphan.py


[databases]
gtdbtk: /home/billy/raid_mount/billy/quackers_db/release226
checkm: /home/billy/raid_mount/billy/quackers_db/checkm

[input]
pair_1: AB_R1_001.fastq
pair_2: AB_R2_001.fastq
output_dir: out_dump